version: '3'

services:
  db-dev:
    image: mariadb:latest
    container_name: db-dev
    ports:
      - 3306:3306
    volumes:
      - db_data_dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  app-dev:
    build:
      context: ../../
      dockerfile: ./docker/development/app/Dockerfile
    container_name: app-dev
    ports:
      - ${PORT}:3000
    volumes:
      - ../../src:/app/src
      - ../../emails:/app/emails
      - ../../public:/app/public
      - ../../next.config.js:/app/next.config.js
    depends_on:
      db-migration-dev:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db-dev:3306/${MYSQL_DATABASE}
      NEXTAUTH_URL: ${DOMAIN}
      NEXT_PUBLIC_DOMAIN: ${DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    restart: always

  db-migration-dev:
    build:
      context: ../../
      dockerfile: ./docker/shared/db-migration/Dockerfile
    container_name: db-migration-dev
    depends_on:
      db-dev:
        condition: service_started
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db-dev:3306/${MYSQL_DATABASE}

volumes:
  db_data_dev:
