query GetMatchesOfCurrentUser {
  getMatchesOfCurrentUser {
    id
    rating
    type
    tutorOffering {
      id
      description
      grade
      schoolSubject {
        id
        name
        longName
      }
      studentId
      teacher {
        id
        longName
        name
        schoolId
      }
    }
    tutorRequest {
      description
      grade
      id
      schoolSubject {
        id
        longName
        name
      }
      studentId
      teacher {
        id
        longName
        name
        schoolId
      }
    }
  }
}

query getMatchConnectionInfo(
  $matchConnectionInfoInput: MatchConnectionInfoInput!
) {
  getMatchConnectionInfo(matchConnectionInfoInput: $matchConnectionInfoInput) {
    student {
      id
      user {
        email
        firstName
        lastName
        name
        id
      }
    }
    schoolClass {
      longName
      name
      id
    }
  }
}

mutation AcceptMatch($acceptMatchInput: AcceptMatchInput!) {
  acceptMatch(acceptMatchInput: $acceptMatchInput)
}
