query GetMatchesOfCurrentUser {
  getMatchesOfCurrentUser {
    id
    rating
    type
    tutorOffering {
      id
      description
      grade
      schoolSubject {
        id
        name
        longName
      }
      studentId
      teacher {
        id
        longName
        name
        schoolId
      }
    }
    tutorRequest {
      description
      grade
      id
      schoolSubject {
        id
        longName
        name
      }
      studentId
      teacher {
        id
        longName
        name
        schoolId
      }
    }
  }
}

mutation AcceptMatch($acceptMatchInput: AcceptMatchInput!) {
  acceptMatch(acceptMatchInput: $acceptMatchInput)
}
