
query GetTutorOfferingById($getTutorOfferingByIdId: Float!) {
  getTutorOfferingById(id: $getTutorOfferingByIdId) {
    description
    grade
    id
    studentId
    schoolSubject {
      name
      longName
      id
    }
    teacher {
      id
      name
      schoolId
    }
  }
}

mutation CreateTutorOffering(
  $tutorOfferingInputCreation: TutorOfferingInputCreation!
) {
  createTutorOffering(TutorOfferingInputCreation: $tutorOfferingInputCreation) {
    description
    grade
    id
    schoolSubject {
      id
      longName
      name
    }
    teacher {
      schoolId
      id
      name
    }
  }
}

mutation UpdateTutorOffering(
  $tutorOfferingUpdateInput: TutorOfferingUpdateInput!
) {
  updateTutorOffering(TutorOfferingUpdateInput: $tutorOfferingUpdateInput) {
    description
    grade
    id
    schoolSubject {
      id
      longName
      name
    }
    teacher {
      schoolId
      id
      name
    }
  }
}
