query GetTutorRequestById($getTutorRequestByIdId: Float!) {
  getTutorRequestById(id: $getTutorRequestByIdId) {
    description
    grade
    id
    schoolSubject {
      name
      longName
      id
    }
    teacher {
      schoolId
      name
      id
    }
  }
}

mutation CreateTutorRequest(
  $tutorRequestCreationInput: TutorRequestCreationInput!
) {
  createTutorRequest(TutorRequestCreationInput: $tutorRequestCreationInput) {
    description
    grade
    id
    schoolSubject {
      name
      longName
      id
    }
    teacher {
      schoolId
      name
      id
    }
  }
}

mutation UpdateTutorRequest(
  $tutorRequestUpdateInput: TutorRequestUpdateInput!
) {
  updateTutorRequest(TutorRequestUpdateInput: $tutorRequestUpdateInput) {
    description
    grade
    id
    schoolSubject {
      name
      longName
      id
    }
    teacher {
      schoolId
      name
      id
    }
  }
}

mutation DeleteTutorRequest($deleteTutorRequestId: Float!) {
  deleteTutorRequest(id: $deleteTutorRequestId) {
    id
  }
}
