query GetSchoolSubjectById($getSchoolSubjectByIdId: Float!) {
  getSchoolSubjectById(id: $getSchoolSubjectByIdId) {
    id
    longName
    name
  }
}

mutation CreateSchoolSubject(
  $schoolSubjectCreationInput: SchoolSubjectCreationInput!
) {
  createSchoolSubject(SchoolSubjectCreationInput: $schoolSubjectCreationInput) {
    id
    longName
    name
  }
}

mutation UpdateSchoolSubject(
  $schoolSubjectUpdateInput: SchoolSubjectUpdateInput!
) {
  updateSchoolSubject(SchoolSubjectUpdateInput: $schoolSubjectUpdateInput) {
    id
    longName
    name
  }
}

mutation DeleteSchoolSubject($deleteSchoolSubjectId: Float!) {
  deleteSchoolSubject(id: $deleteSchoolSubjectId) {
    id
  }
}

query GetAdministeredSchoolSubjects {
  getAdministeredSchool {
    schoolSubjects {
      id
      longName
      name
    }
  }
}
