query GetSchoolById($getSchoolByIdId: Float!) {
  getSchoolById(id: $getSchoolByIdId) {
    domain
    id
    name
    departments {
      longName
      name
      id
    }
  }
}

query GetAdministeredSchool {
  getAdministeredSchool {
    name
    domain
    id
  }
}

mutation CreateSchool($schoolCreationInput: SchoolCreationInput!) {
  createSchool(schoolCreationInput: $schoolCreationInput) {
    id
    name
    domain
  }
}

mutation UpdateSchool($schoolUpdateInput: SchoolUpdateInput!) {
  updateSchool(schoolUpdateInput: $schoolUpdateInput) {
    id
    name
    domain
  }
}

mutation DeleteSchool($deleteSchoolId: Float!) {
  deleteSchool(id: $deleteSchoolId) {
    id
  }
}

query GetSchoolClassesOfSchool {
  getSchoolClassesOfSchool {
    longName
    name
    id
  }
}
