query GetSchoolById($getSchoolByIdId: Float!) {
  getSchoolById(id: $getSchoolByIdId) {
    name
    domain
    id
    departments {
      id
      longName
      name
    }
    admins {
      id
      user {
        name
        email
        id
      }
    }
  }
}

query GetAdministeredSchool {
  getAdministeredSchool {
    id
  }
}

mutation CreateSchool($schoolCreationInput: SchoolCreationInput!) {
  createSchool(schoolCreationInput: $schoolCreationInput) {
    id
    name
    domain
  }
}

mutation UpdateSchool($schoolUpdateInput: SchoolUpdateInput!) {
  updateSchool(schoolUpdateInput: $schoolUpdateInput) {
    id
    name
    domain
  }
}

query GetSchoolClassesOfSchool {
  getSchoolClassesOfSchool {
    longName
    name
    id
  }
}
