query GetSchoolClassById($getSchoolClassByIdId: Float!) {
  getSchoolClassById(id: $getSchoolClassByIdId) {
    id
    name
    longName
  }
}
mutation CreateSchoolClass($schoolClassCreateInput: SchoolClassCreationInput!) {
  createSchoolClass(schoolClassCreateInput: $schoolClassCreateInput) {
    id
    name
    longName
  }
}
mutation UpdateSchoolClass($schoolClassUpdateInput: SchoolClassUpdateInput!) {
  updateSchoolClass(schoolClassUpdateInput: $schoolClassUpdateInput) {
    id
    name
    longName
  }
}
mutation DeleteSchoolClass($deleteSchoolClassId: Float!) {
  deleteSchoolClass(id: $deleteSchoolClassId) {
    id
  }
}
