query getStudentById($getStudentByIdId: Float!) {
  getStudentById(id: $getStudentByIdId) {
    id
    user {
      email
      name
      firstName
      lastName
    }
    schoolClassId
  }
}

mutation createStudent($studentInput: StudentCreationInput!) {
  createStudent(studentInput: $studentInput) {
    id
    user {
      email
      name
      firstName
      lastName
    }
    schoolClassId
  }
}

mutation updateStudent($studentInput: StudentUpdateInput!) {
  updateStudent(studentInput: $studentInput) {
    id
    user {
      email
      name
      firstName
      lastName
    }
    schoolClassId
  }
}

mutation DeleteStudent($deleteStudentId: Float!) {
  deleteStudent(id: $deleteStudentId) {
    id
  }
}

query GetStudentOfCurrentUser {
  getStudentOfCurrentUser {
    tutorOfferings {
      description
      grade
      id
      schoolSubject {
        name
        longName
        id
      }
      teacher {
        name
        longName
        id
      }
    }
    tutorRequests {
      description
      grade
      id
      schoolSubject {
        name
        longName
        id
      }
      teacher {
        schoolId
        name
        longName
        id
      }
    }
    id
    user {
      email
      id
      name
    }
    schoolClassId
  }
}

query getSubjectsOfStudent {
  getSubjectsOfStudent {
    id
    longName
    name
  }
}

query GetTeachersOfStudent {
  getTeachersOfStudent {
    name
    schoolId
    id
  }
}

query GetAdministeredStudents {
  getAdministeredSchool {
    departments {
      schoolClasses {
        students {
          id
          user {
            name
            id
            email
          }
          schoolClassId
        }
        departmentId
        name
      }
      name
    }
  }
}
