query GetCurrentUser {
  getCurrentUser {
    id
    email
    name
    id
    role
  }
}

query GetUserName {
  getCurrentUser {
    id
    name
  }
}

mutation UpdateUser($userUpdateInput: UserUpdateInput!) {
  updateUser(userUpdateInput: $userUpdateInput) {
    email
    name
    id
    role
  }
}

mutation ForgotPassword($forgotPasswordInput: ForgotPasswordInput!) {
  forgotPassword(forgotPasswordInput: $forgotPasswordInput)
}

mutation ResetPassword($resetPasswordInput: ResetPasswordInput!) {
  resetPassword(resetPasswordInput: $resetPasswordInput)
}

mutation VerifyEmail($verifyEmailInput: VerifyEmailInput!) {
  verifyEmail(verifyEmailInput: $verifyEmailInput)
}

mutation DeleteOwnUser {
  deleteOwnUser {
    id
  }
}
