version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studylink
    restart: always

  studylink:
    build: ./docker/app/dev
    container_name: studylink
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env.example

volumes:
  mysql_data:
