version: '3'

services:
  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  app:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    container_name: studylink
    volumes:
      - .:/app
    ports:
      - ${PORT}:3000
    depends_on:
      db_migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      NEXTAUTH_URL: ${DOMAIN}
      DOMAIN: ${DOMAIN}
      NEXT_PUBLIC_DOMAIN: ${DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    restart: always

  db_migration:
    build:
      context: ..
      dockerfile: docker/db_migration/Dockerfile
    container_name: db_migration
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}

volumes:
  db_data:
