version: '3'

services:
  db_dev:
    image: mariadb:latest
    container_name: db_dev
    ports:
      - 3306:3306
    volumes:
      - db_data_dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  app_dev:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: studylink_dev
    ports:
      - ${PORT}:3000
    volumes:
      - .:/app
    depends_on:
      db_migration_dev:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db_dev:3306/${MYSQL_DATABASE}
      NEXTAUTH_URL: ${DOMAIN}
      DOMAIN: ${DOMAIN}
      NEXT_PUBLIC_DOMAIN: ${DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
    restart: always
    command: npm run dev

  db_migration_dev:
    build:
      context: ..
      dockerfile: docker/db_migration/Dockerfile
    container_name: db_migration_dev
    depends_on:
      db_dev:
        condition: service_started
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db_dev:3306/${MYSQL_DATABASE}

volumes:
  db_data_dev:
