version: '3'

services:
  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  nginx:
    build:
      context: ../../
      dockerfile: ./docker/production/nginx/Dockerfile
    container_name: nginx
    ports:
      - ${PORT}:80
    depends_on:
      app:
        condition: service_started
    volumes:
      - nginx_logs:/var/log/nginx/:rw
    restart: always

  app:
    build:
      context: ../../
      dockerfile: ./docker/production/app/Dockerfile
    container_name: app
    expose:
      - 3000
    depends_on:
      db-migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      NEXTAUTH_URL: ${DOMAIN}
      NEXT_PUBLIC_DOMAIN: ${DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    restart: always

  db-migration:
    build:
      context: ../../
      dockerfile: ./docker/shared/db-migration/Dockerfile
    container_name: db-migration
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}

volumes:
  db_data:
  nginx_logs:
